# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1
image:
  repository: localhost:5000/my-go-app
  tag: latest
  pullPolicy: Never
  resources:
    requests:
      cpu: 200m
      memory: 300Mi
  readinessProbe:
    httpGet:
      path: /readyz
      port: 8001
      initialDelaySeconds: 3
      periodSeconds: 5
  livenessProbe:
    httpGet:
      path: /healthz
      port: 8001
      initialDelaySeconds: 40
      periodSeconds: 10
service:
  name: Node
  type: NodePort
  servicePort: 30640
  targetPort: 8001
  port: 8001
