kind: Service
apiVersion: v1
metadata:
  name: {{  .Chart.Name }}
  labels:
    {{- include "restapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      nodePort:  {{ .Values.service.servicePort }}
  selector:
    app: {{  .Chart.Name }}
    version: current
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer: {}
